-- Phase 2 - Affectation automatique + file d'intervention
-- A executer APRES:
-- 1) supabase/schema.sql
-- 2) supabase/admin_backoffice.sql

alter table public.reports add column if not exists assigned_service text;
alter table public.reports add column if not exists assigned_user_id uuid;
alter table public.reports add column if not exists assigned_priority text default 'NORMAL';
alter table public.reports add column if not exists assigned_due_at timestamptz;
alter table public.reports add column if not exists assigned_note text;
alter table public.reports add column if not exists assigned_at timestamptz;
alter table public.reports add column if not exists assigned_by uuid;
alter table public.reports add column if not exists assignment_source text default 'manual';

alter table public.reports drop constraint if exists reports_assigned_service_check;
alter table public.reports
add constraint reports_assigned_service_check
check (
  assigned_service is null
  or assigned_service in ('VOIRIE', 'ECLAIRAGE', 'ASSAINISSEMENT', 'SECURITE', 'INONDATION', 'GENERAL', 'AUTRE')
);

alter table public.reports drop constraint if exists reports_assigned_priority_check;
alter table public.reports
add constraint reports_assigned_priority_check
check (
  assigned_priority is null
  or assigned_priority in ('LOW', 'NORMAL', 'HIGH', 'URGENT')
);

alter table public.reports drop constraint if exists reports_assignment_source_check;
alter table public.reports
add constraint reports_assignment_source_check
check (
  assignment_source is null
  or assignment_source in ('manual', 'auto', 'ai')
);

create index if not exists idx_reports_assigned_service_status
on public.reports (assigned_service, status, created_at desc);

create index if not exists idx_reports_assigned_user_status
on public.reports (assigned_user_id, status, created_at desc);

create table if not exists public.report_assignments (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  service text not null,
  assigned_user_id uuid,
  priority text not null default 'NORMAL',
  due_at timestamptz,
  note text,
  source text not null default 'manual',
  assigned_by uuid,
  created_at timestamptz not null default now(),
  constraint report_assignments_service_check
    check (service in ('VOIRIE', 'ECLAIRAGE', 'ASSAINISSEMENT', 'SECURITE', 'INONDATION', 'GENERAL', 'AUTRE')),
  constraint report_assignments_priority_check
    check (priority in ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
  constraint report_assignments_source_check
    check (source in ('manual', 'auto', 'ai'))
);

create index if not exists idx_report_assignments_report_id_created_at
on public.report_assignments (report_id, created_at desc);

create index if not exists idx_report_assignments_service_created_at
on public.report_assignments (service, created_at desc);

alter table public.report_assignments enable row level security;

drop policy if exists "report_assignments_select_operator" on public.report_assignments;
drop policy if exists "report_assignments_insert_operator" on public.report_assignments;
drop policy if exists "report_assignments_update_admin" on public.report_assignments;

create policy "report_assignments_select_operator" on public.report_assignments
for select
to authenticated
using (public.is_operator());

create policy "report_assignments_insert_operator" on public.report_assignments
for insert
to authenticated
with check (public.is_operator());

create policy "report_assignments_update_admin" on public.report_assignments
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create or replace function public.map_report_service(
  p_type text,
  p_ai_priority text default null,
  p_description text default null
)
returns text
language plpgsql
stable
as $$
declare
  v_type text := upper(trim(coalesce(p_type, 'AUTRE')));
  v_desc text := lower(trim(coalesce(p_description, '')));
begin
  if v_type = 'VOIRIE' then return 'VOIRIE'; end if;
  if v_type = 'ECLAIRAGE' then return 'ECLAIRAGE'; end if;
  if v_type = 'DECHETS' then return 'ASSAINISSEMENT'; end if;
  if v_type = 'INONDATION' then return 'INONDATION'; end if;
  if v_type = 'SECURITE' then return 'SECURITE'; end if;

  if v_desc like '%eau%' or v_desc like '%caniveau%' or v_desc like '%pluie%' then
    return 'INONDATION';
  end if;
  if v_desc like '%ordure%' or v_desc like '%dechet%' then
    return 'ASSAINISSEMENT';
  end if;
  if v_desc like '%route%' or v_desc like '%trou%' or v_desc like '%chauss%' then
    return 'VOIRIE';
  end if;
  if v_desc like '%lumiere%' or v_desc like '%ampoule%' or v_desc like '%obscur%' then
    return 'ECLAIRAGE';
  end if;
  if v_desc like '%vol%' or v_desc like '%agression%' or v_desc like '%police%' then
    return 'SECURITE';
  end if;

  return 'GENERAL';
end;
$$;

create or replace function public.map_report_assignment_priority(
  p_ai_priority text,
  p_type text
)
returns text
language plpgsql
stable
as $$
declare
  v_ai text := upper(trim(coalesce(p_ai_priority, '')));
  v_type text := upper(trim(coalesce(p_type, 'AUTRE')));
begin
  if v_ai = 'HIGH' then return 'URGENT'; end if;
  if v_ai = 'MEDIUM' then return 'HIGH'; end if;
  if v_ai = 'LOW' then return 'NORMAL'; end if;
  if v_type in ('SECURITE', 'INONDATION') then return 'HIGH'; end if;
  return 'NORMAL';
end;
$$;

create or replace function public.list_active_operators()
returns table (
  user_id uuid,
  email text,
  full_name text,
  role text
)
language sql
stable
security definer
set search_path = public
as $$
  select p.user_id, p.email, p.full_name, p.role
  from public.profiles p
  where p.is_active = true
    and p.role in ('admin', 'agent')
    and public.is_operator()
  order by
    case when p.role = 'admin' then 0 else 1 end,
    coalesce(p.full_name, p.email);
$$;

grant execute on function public.list_active_operators() to authenticated;

create or replace function public.apply_report_assignment(
  p_report_id bigint,
  p_service text default null,
  p_assigned_user_id uuid default null,
  p_due_at timestamptz default null,
  p_priority text default null,
  p_note text default null,
  p_source text default 'manual'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.reports%rowtype;
  v_service text;
  v_priority text;
  v_due_at timestamptz;
  v_source text := lower(trim(coalesce(p_source, 'manual')));
begin
  if not public.is_operator() then
    raise exception 'forbidden';
  end if;

  select * into v_report
  from public.reports
  where id = p_report_id
  limit 1;

  if v_report.id is null then
    raise exception 'report not found';
  end if;

  v_service := upper(trim(coalesce(p_service, '')));
  if v_service = '' then
    v_service := public.map_report_service(v_report.type, v_report.ai_priority, v_report.description);
  end if;

  v_priority := upper(trim(coalesce(p_priority, '')));
  if v_priority = '' then
    v_priority := public.map_report_assignment_priority(v_report.ai_priority, v_report.type);
  end if;

  v_due_at := p_due_at;
  if v_due_at is null then
    if v_priority = 'URGENT' then
      v_due_at := now() + interval '12 hours';
    elsif v_priority = 'HIGH' then
      v_due_at := now() + interval '1 day';
    elsif v_priority = 'NORMAL' then
      v_due_at := now() + interval '3 days';
    else
      v_due_at := now() + interval '5 days';
    end if;
  end if;

  update public.reports
  set assigned_service = v_service,
      assigned_user_id = p_assigned_user_id,
      assigned_priority = v_priority,
      assigned_due_at = v_due_at,
      assigned_note = nullif(trim(coalesce(p_note, '')), ''),
      assigned_at = now(),
      assigned_by = auth.uid(),
      assignment_source = case when v_source in ('manual', 'auto', 'ai') then v_source else 'manual' end
  where id = p_report_id;

  insert into public.report_assignments (
    report_id, service, assigned_user_id, priority, due_at, note, source, assigned_by
  ) values (
    p_report_id, v_service, p_assigned_user_id, v_priority, v_due_at,
    nullif(trim(coalesce(p_note, '')), ''),
    case when v_source in ('manual', 'auto', 'ai') then v_source else 'manual' end,
    auth.uid()
  );

  return jsonb_build_object(
    'ok', true,
    'report_id', p_report_id,
    'service', v_service,
    'priority', v_priority,
    'due_at', v_due_at,
    'assigned_user_id', p_assigned_user_id,
    'source', v_source
  );
end;
$$;

grant execute on function public.apply_report_assignment(bigint, text, uuid, timestamptz, text, text, text) to authenticated;

create or replace function public.auto_assign_open_reports(
  p_limit integer default 40,
  p_only_unassigned boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 40), 250));
  v_row record;
  v_count integer := 0;
begin
  if not public.is_operator() then
    raise exception 'forbidden';
  end if;

  for v_row in
    select r.id
    from public.reports r
    where r.status = 'NOUVEAU'
      and (
        p_only_unassigned = false
        or r.assigned_service is null
      )
    order by r.created_at asc
    limit v_limit
  loop
    perform public.apply_report_assignment(
      v_row.id,
      null,
      null,
      null,
      null,
      'Affectation automatique',
      'auto'
    );
    v_count := v_count + 1;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'processed', v_count,
    'limit', v_limit
  );
end;
$$;

grant execute on function public.auto_assign_open_reports(integer, boolean) to authenticated;

