create table if not exists public.poi (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  address text,
  phone text,
  description text,
  status text default 'ACTIF',
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  status text not null default 'NOUVEAU',
  description text,
  latitude double precision not null,
  longitude double precision not null,
  source_hash text,
  created_at timestamptz default now()
);

create index if not exists idx_reports_source_hash_created_at
on public.reports (source_hash, created_at desc);

alter table public.poi enable row level security;
alter table public.reports enable row level security;

drop policy if exists "poi_select_public" on public.poi;
drop policy if exists "poi_insert_public" on public.poi;
drop policy if exists "reports_select_public" on public.reports;
drop policy if exists "reports_insert_public" on public.reports;
drop policy if exists "poi_insert_authenticated" on public.poi;
drop policy if exists "reports_insert_authenticated" on public.reports;

create policy "poi_select_public" on public.poi
for select
to anon
using (true);

create policy "poi_insert_authenticated" on public.poi
for insert
to authenticated
with check (true);

create policy "reports_select_public" on public.reports
for select
to anon
using (true);

create policy "reports_insert_authenticated" on public.reports
for insert
to authenticated
with check (true);
