create table if not exists public.poi (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  address text,
  phone text,
  description text,
  photo_url text,
  photo_path text,
  photo_taken_at timestamptz,
  status text default 'ACTIF',
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz default now()
);

alter table public.poi add column if not exists photo_url text;
alter table public.poi add column if not exists photo_path text;
alter table public.poi add column if not exists photo_taken_at timestamptz;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  status text not null default 'NOUVEAU',
  description text,
  latitude double precision not null,
  longitude double precision not null,
  source_hash text,
  ai_suggested_type text,
  ai_priority text,
  ai_summary text,
  ai_confidence double precision,
  ai_reason text,
  ai_model text,
  ai_processed_at timestamptz,
  created_at timestamptz default now()
);

alter table public.reports add column if not exists ai_suggested_type text;
alter table public.reports add column if not exists ai_priority text;
alter table public.reports add column if not exists ai_summary text;
alter table public.reports add column if not exists ai_confidence double precision;
alter table public.reports add column if not exists ai_reason text;
alter table public.reports add column if not exists ai_model text;
alter table public.reports add column if not exists ai_processed_at timestamptz;

alter table public.reports drop constraint if exists reports_ai_priority_check;
alter table public.reports
add constraint reports_ai_priority_check
check (ai_priority is null or ai_priority in ('LOW', 'MEDIUM', 'HIGH'));

create index if not exists idx_reports_source_hash_created_at
on public.reports (source_hash, created_at desc);

alter table public.poi enable row level security;
alter table public.reports enable row level security;

drop policy if exists "poi_select_public" on public.poi;
drop policy if exists "poi_insert_public" on public.poi;
drop policy if exists "reports_select_public" on public.reports;
drop policy if exists "reports_insert_public" on public.reports;
drop policy if exists "poi_insert_authenticated" on public.poi;
drop policy if exists "reports_insert_authenticated" on public.reports;

create policy "poi_select_public" on public.poi
for select
to anon
using (true);

create policy "poi_insert_authenticated" on public.poi
for insert
to authenticated
with check (true);

create policy "reports_select_public" on public.reports
for select
to anon
using (true);

create policy "reports_insert_authenticated" on public.reports
for insert
to authenticated
with check (true);
