create table if not exists public.poi (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  address text,
  phone text,
  description text,
  photo_url text,
  photo_path text,
  photo_taken_at timestamptz,
  status text default 'ACTIF',
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz default now()
);

alter table public.poi add column if not exists photo_url text;
alter table public.poi add column if not exists photo_path text;
alter table public.poi add column if not exists photo_taken_at timestamptz;

alter table public.poi drop constraint if exists poi_status_check;
alter table public.poi
add constraint poi_status_check
check (status in ('ACTIF', 'INACTIF'));

alter table public.poi drop constraint if exists poi_latitude_range_check;
alter table public.poi
add constraint poi_latitude_range_check
check (latitude >= -90 and latitude <= 90);

alter table public.poi drop constraint if exists poi_longitude_range_check;
alter table public.poi
add constraint poi_longitude_range_check
check (longitude >= -180 and longitude <= 180);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  status text not null default 'NOUVEAU',
  description text,
  latitude double precision not null,
  longitude double precision not null,
  source_hash text,
  ai_suggested_type text,
  ai_priority text,
  ai_summary text,
  ai_confidence double precision,
  ai_reason text,
  ai_model text,
  ai_processed_at timestamptz,
  assigned_service text,
  assigned_user_id uuid,
  assigned_priority text default 'NORMAL',
  assigned_due_at timestamptz,
  assigned_note text,
  assigned_at timestamptz,
  assigned_by uuid,
  assignment_source text default 'manual',
  created_at timestamptz default now()
);

alter table public.reports add column if not exists ai_suggested_type text;
alter table public.reports add column if not exists ai_priority text;
alter table public.reports add column if not exists ai_summary text;
alter table public.reports add column if not exists ai_confidence double precision;
alter table public.reports add column if not exists ai_reason text;
alter table public.reports add column if not exists ai_model text;
alter table public.reports add column if not exists ai_processed_at timestamptz;
alter table public.reports add column if not exists assigned_service text;
alter table public.reports add column if not exists assigned_user_id uuid;
alter table public.reports add column if not exists assigned_priority text default 'NORMAL';
alter table public.reports add column if not exists assigned_due_at timestamptz;
alter table public.reports add column if not exists assigned_note text;
alter table public.reports add column if not exists assigned_at timestamptz;
alter table public.reports add column if not exists assigned_by uuid;
alter table public.reports add column if not exists assignment_source text default 'manual';

alter table public.reports drop constraint if exists reports_type_check;
alter table public.reports
add constraint reports_type_check
check (type in ('VOIRIE', 'ECLAIRAGE', 'DECHETS', 'INONDATION', 'SECURITE', 'AUTRE'));

alter table public.reports drop constraint if exists reports_status_check;
alter table public.reports
add constraint reports_status_check
check (status in ('NOUVEAU', 'EN_COURS', 'RESOLU'));

alter table public.reports drop constraint if exists reports_ai_priority_check;
alter table public.reports
add constraint reports_ai_priority_check
check (ai_priority is null or ai_priority in ('LOW', 'MEDIUM', 'HIGH'));

alter table public.reports drop constraint if exists reports_assigned_service_check;
alter table public.reports
add constraint reports_assigned_service_check
check (
  assigned_service is null
  or assigned_service in ('VOIRIE', 'ECLAIRAGE', 'ASSAINISSEMENT', 'SECURITE', 'INONDATION', 'GENERAL', 'AUTRE')
);

alter table public.reports drop constraint if exists reports_assigned_priority_check;
alter table public.reports
add constraint reports_assigned_priority_check
check (
  assigned_priority is null
  or assigned_priority in ('LOW', 'NORMAL', 'HIGH', 'URGENT')
);

alter table public.reports drop constraint if exists reports_assignment_source_check;
alter table public.reports
add constraint reports_assignment_source_check
check (
  assignment_source is null
  or assignment_source in ('manual', 'auto', 'ai')
);

alter table public.reports drop constraint if exists reports_latitude_range_check;
alter table public.reports
add constraint reports_latitude_range_check
check (latitude >= -90 and latitude <= 90);

alter table public.reports drop constraint if exists reports_longitude_range_check;
alter table public.reports
add constraint reports_longitude_range_check
check (longitude >= -180 and longitude <= 180);

create index if not exists idx_reports_source_hash_created_at
on public.reports (source_hash, created_at desc);

create index if not exists idx_poi_category_status_created_at
on public.poi (category, status, created_at desc);

create index if not exists idx_reports_type_status_created_at
on public.reports (type, status, created_at desc);

create index if not exists idx_reports_status_created_at
on public.reports (status, created_at desc);

create index if not exists idx_reports_assigned_service_status
on public.reports (assigned_service, status, created_at desc);

create index if not exists idx_reports_assigned_user_status
on public.reports (assigned_user_id, status, created_at desc);

alter table public.poi enable row level security;
alter table public.reports enable row level security;

drop policy if exists "poi_select_public" on public.poi;
drop policy if exists "poi_insert_public" on public.poi;
drop policy if exists "poi_select_authenticated" on public.poi;
drop policy if exists "reports_select_public" on public.reports;
drop policy if exists "reports_insert_public" on public.reports;
drop policy if exists "reports_select_authenticated" on public.reports;
drop policy if exists "poi_insert_authenticated" on public.poi;
drop policy if exists "reports_insert_authenticated" on public.reports;

create policy "poi_select_public" on public.poi
for select
to anon
using (true);

create policy "poi_select_authenticated" on public.poi
for select
to authenticated
using (true);

create policy "reports_select_public" on public.reports
for select
to anon
using (true);

create policy "reports_select_authenticated" on public.reports
for select
to authenticated
using (true);
